# Generated by Django 5.2.15 on 2026-06-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockexit'),
        ('tenancy', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_layers', to='inventory.item')),
                ('stock_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_layer', to='inventory.stockentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_layers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['entry_date', 'id'],
            },
        ),
    ]
