# Generated by Django 5.2.15 on 2026-06-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocklayer'),
        ('tenancy', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockexit')),
                ('stock_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_allocations', to='inventory.stocklayer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
