# Generated by Django 5.2.15 on 2026-06-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryadjustmentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklayer',
            name='stock_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_layer', to='inventory.stockentry'),
        ),
    ]
