# Generated by Django 5.2.15 on 2026-06-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stocktransfer_stocktransferallocation'),
        ('tenancy', '0005_tenant_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFVRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=5, max_digits=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
