# Generated by Django 5.2.15 on 2026-06-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_ufvrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='ufv_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='inventory.ufvrate'),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='ufv_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
