# Generated by Django 5.2.15 on 2026-06-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_stockentry_ufv_rate_stockentry_ufv_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklayer',
            name='ufv_value',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
    ]
