# Generated by Django 5.2.15 on 2026-06-22 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stocklayer_ufv_value'),
        ('tenancy', '0005_tenant_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UFVRevaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closing_date', models.DateField()),
                ('closing_ufv', models.DecimalField(decimal_places=5, max_digits=12)),
                ('total_original_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_updated_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_revaluation', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ufv_revaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['-closing_date', '-id'],
                'unique_together': {('tenant', 'closing_date')},
            },
        ),
        migrations.CreateModel(
            name='UFVRevaluationRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_ufv', models.DecimalField(decimal_places=5, max_digits=12)),
                ('closing_ufv', models.DecimalField(decimal_places=5, max_digits=12)),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('updated_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('revaluation_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.ufvrevaluationrun')),
                ('stock_layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ufv_revaluation_lines', to='inventory.stocklayer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
