# Generated by Django 5.2.15 on 2026-06-22 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockentrydocument_stockentryline_stockexitdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklayer',
            name='stock_entry_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_layer', to='inventory.stockentryline'),
        ),
    ]
