# Generated by Django 5.2.15 on 2026-06-25 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_documentsequence'),
        ('tenancy', '0005_tenant_company_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockentrydocument',
            unique_together={('tenant', 'document_number')},
        ),
        migrations.AlterUniqueTogether(
            name='stockexitdocument',
            unique_together={('tenant', 'document_number')},
        ),
    ]
