# Generated by Django 5.2.15 on 2026-06-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_stockentrydocument_unique_together_and_more'),
        ('tenancy', '0005_tenant_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('movement_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('both', 'Both')], max_length=20)),
                ('requires_supplier', models.BooleanField(default=False)),
                ('requires_supplier_tax_id', models.BooleanField(default=False)),
                ('requires_requester', models.BooleanField(default=False)),
                ('requires_requesting_unit', models.BooleanField(default=False)),
                ('requires_pdf', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'ordering': ['movement_type', 'code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
    ]
