# Generated by Django 5.2.15 on 2026-06-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_documenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentrydocument',
            name='document_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_documents', to='inventory.documenttype'),
        ),
        migrations.AddField(
            model_name='stockexitdocument',
            name='document_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exit_documents', to='inventory.documenttype'),
        ),
    ]
