# Generated by Django 5.2.15 on 2026-06-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenant_address_tenant_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos/'),
        ),
    ]
