# Generated by Django 5.2.15 on 2026-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_tenant_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='document_number_format',
            field=models.CharField(default='{code}-{year}-{number}', max_length=100),
        ),
    ]
