# Generated by Django 5.2.11 on 2026-03-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('entity', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=300)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenancy.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='core_auditl_tenant__5f83c4_idx'), models.Index(fields=['tenant', 'action'], name='core_auditl_tenant__f59c2a_idx'), models.Index(fields=['tenant', 'entity', 'entity_id'], name='core_auditl_tenant__c044b4_idx'), models.Index(fields=['request_id'], name='core_auditl_request_2f651b_idx')],
            },
        ),
    ]
