from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
import logging
from tempfile import NamedTemporaryFile

from reportlab.lib.utils import ImageReader
from decimal import Decimal

from datetime import datetime

from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


logger = logging.getLogger(__name__)


def add_pdf_tenant_header(elements, tenant, styles, report_title, user=None):
    if tenant.company_logo:
        try:
            with tenant.company_logo.open("rb") as logo_file:
                logo_buffer = BytesIO(logo_file.read())
                logo_buffer.seek(0)

                logo = Image(logo_buffer, width=140, height=55)
                elements.append(logo)
                elements.append(Spacer(1, 8))
        except Exception as exc:
            logger.exception("Could not add tenant logo to PDF: %s", exc)

    company_name = tenant.company_name or tenant.name

    elements.append(Paragraph(company_name, styles["Title"]))

    if tenant.tax_id:
        elements.append(Paragraph(f"NIT: {tenant.tax_id}", styles["Normal"]))

    if tenant.address:
        elements.append(Paragraph(f"Address: {tenant.address}", styles["Normal"]))

    if tenant.phone:
        elements.append(Paragraph(f"Phone: {tenant.phone}", styles["Normal"]))

    elements.append(Spacer(1, 18))
    elements.append(Paragraph(report_title, styles["Heading2"]))
    elements.append(Spacer(1, 8))

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M")
    elements.append(
        Paragraph(
            f"Generated at: {generated_at}",
            styles["Normal"],
        )
    )

    if user and user.is_authenticated:
        elements.append(
            Paragraph(
                f"Generated by: {user.get_username()}",
                styles["Normal"],
            )
        )

    elements.append(Spacer(1, 12))


def add_pdf_footer(canvas, doc):
    canvas.saveState()

    footer_text = f"Exventory · Page {doc.page}"
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)

    canvas.drawRightString(
        doc.pagesize[0] - doc.rightMargin,
        18,
        footer_text,
    )

    canvas.restoreState()


def build_pdf_buffer(elements, pagesize=letter):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=pagesize,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    doc.build(
        elements,
        onFirstPage=add_pdf_footer,
        onLaterPages=add_pdf_footer,
    )

    buffer.seek(0)
    return buffer


def build_inventory_valuation_pdf(tenant, data, user=None):
    styles = getSampleStyleSheet()
    elements = []

    add_pdf_tenant_header(
        elements,
        tenant,
        styles,
        "Inventory Valuation Report",
        user=user,
    )

    table_data = [["Warehouse", "Inventory Value"]]

    for warehouse in data["warehouses"]:
        table_data.append([
            warehouse["warehouse_name"],
            warehouse["inventory_value"],
        ])

    table_data.append(["TOTAL", data["total_inventory_value"]])

    table = Table(table_data, colWidths=[330, 150])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (1, 1), (1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#F1F5F9")),
    ]))

    elements.append(table)

    return build_pdf_buffer(elements)


def build_current_stock_pdf(tenant, rows, user=None):
    styles = getSampleStyleSheet()
    elements = []

    add_pdf_tenant_header(
        elements,
        tenant,
        styles,
        "Current Stock Report",
    )

    table_data = [
        [
            "Warehouse",
            "Item",
            "Quantity",
            "Avg Cost",
            "Total Cost",
        ]
    ]

    total_value = Decimal("0")

    for row in rows:
        total_value += Decimal(str(row["total_cost"]))

        table_data.append([
            row["warehouse_name"],
            f'{row["item_code"]} - {row["item_name"]}',
            row["quantity"],
            row["average_cost"],
            row["total_cost"],
        ])

    table_data.append([
        "TOTAL",
        "",
        "",
        "",
        str(total_value.quantize(Decimal("0.01"))),
    ])

    table = Table(table_data, colWidths=[110, 190, 70, 80, 80])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (2, 1), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#F1F5F9")),
    ]))

    elements.append(table)

    return build_pdf_buffer(elements)


def build_kardex_pdf(tenant, rows, user=None):
    styles = getSampleStyleSheet()
    elements = []

    add_pdf_tenant_header(
        elements,
        tenant,
        styles,
        "Kardex Report",
    )

    table_data = [
        [
            "Date",
            "Type",
            "Reference",
            "Entry",
            "Exit",
            "Balance",
            "Unit Cost",
            "Mov. Cost",
            "Balance Value",
            "Avg Cost",
        ]
    ]

    for row in rows:
        table_data.append([
            row["date"],
            row["type"],
            row["reference"] or "-",
            row["entry_quantity"],
            row["exit_quantity"],
            row["balance_quantity"],
            row["unit_cost"],
            row["total_cost"],
            row["balance_value"],
            row["average_balance_cost"],
        ])

    table = Table(
        table_data,
        colWidths=[55, 78, 85, 45, 45, 55, 55, 60, 70, 55],
        repeatRows=1,
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1E293B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("ALIGN", (3, 1), (-1, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    elements.append(table)

    return build_pdf_buffer(elements)
