import { useParams, useNavigate } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";

import { useTenant } from "../../context/TenantContext";
import { getUFVRevaluationRun } from "./api";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export function UFVRevaluationRunDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { tenantSlug } = useTenant();

  const runId = Number(id);

  const {
    data: run,
    isLoading,
    isError,
  } = useQuery({
    queryKey: ["ufv-revaluation-run", tenantSlug, runId],
    queryFn: () => getUFVRevaluationRun(runId),
    enabled: Number.isFinite(runId) && runId > 0,
  });

  return (
    <section className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">
            UFV Revaluation Run Detail
          </h2>
          <p className="text-muted-foreground">
            Review the detail lines generated by this UFV revaluation.
          </p>
        </div>

        <Button variant="outline" onClick={() => navigate("/ufv-revaluation-runs")}>
          Back
        </Button>
      </div>

      {isLoading && <p className="text-muted-foreground">Loading...</p>}

      {isError && (
        <p className="text-sm text-red-600">
          Could not load UFV revaluation run.
        </p>
      )}

      {run && (
        <>
          <div className="grid gap-4 md:grid-cols-3">
            <Card>
              <CardHeader>
                <CardTitle className="text-sm text-muted-foreground">
                  Closing Date
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">{run.closing_date}</p>
                <p className="text-sm text-muted-foreground">
                  UFV {run.closing_ufv}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-sm text-muted-foreground">
                  Updated Value
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">
                  {run.total_updated_value}
                </p>
                <p className="text-sm text-muted-foreground">
                  Original {run.total_original_value}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="text-sm text-muted-foreground">
                  Revaluation
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">
                  {run.total_revaluation}
                </p>
                <p className="text-sm text-muted-foreground">
                  Applied by {run.applied_by_username ?? "-"}
                </p>
              </CardContent>
            </Card>
          </div>

          {run.notes && (
            <Card>
              <CardHeader>
                <CardTitle>Notes</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm">{run.notes}</p>
              </CardContent>
            </Card>
          )}

          <Card>
            <CardHeader>
              <CardTitle>Lines</CardTitle>
            </CardHeader>

            <CardContent>
              {run.lines.length === 0 ? (
                <p className="text-muted-foreground">No lines found.</p>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Warehouse</TableHead>
                      <TableHead>Item</TableHead>
                      <TableHead className="text-right">Qty</TableHead>
                      <TableHead className="text-right">Purchase UFV</TableHead>
                      <TableHead className="text-right">Closing UFV</TableHead>
                      <TableHead className="text-right">Original Total</TableHead>
                      <TableHead className="text-right">Updated Total</TableHead>
                      <TableHead className="text-right">Revaluation</TableHead>
                    </TableRow>
                  </TableHeader>

                  <TableBody>
                    {run.lines.map((line) => (
                      <TableRow key={line.id}>
                        <TableCell>{line.warehouse_name}</TableCell>
                        <TableCell>
                          {line.item_code} - {line.item_name}
                        </TableCell>
                        <TableCell className="text-right">
                          {line.quantity}
                        </TableCell>
                        <TableCell className="text-right">
                          {line.purchase_ufv}
                        </TableCell>
                        <TableCell className="text-right">
                          {line.closing_ufv}
                        </TableCell>
                        <TableCell className="text-right">
                          {line.original_total}
                        </TableCell>
                        <TableCell className="text-right">
                          {line.updated_total}
                        </TableCell>
                        <TableCell className="text-right font-medium">
                          {line.revaluation_amount}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>
        </>
      )}
    </section>
  );
}
